; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Match the Serial.begin() speed in your code
monitor_speed = 115200 

; Forces the compiler to check the src/ directory for all your sub-folder header files
build_flags = 
    -I src

; The external libraries PlatformIO needs to download
lib_deps =
    ; 1. OLED Display Drivers
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SH110X @ ^2.1.10
    
    ; 2. Asynchronous Web Tuner & WebSockets
    mathieucarbou/ESPAsyncWebServer @ ^3.3.2
    
    ; 3. JSON Parsing for the Web Tuner payloads
    bblanchon/ArduinoJson @ ^7.0.4